global.hideRemoveJEI = [
    "minecraft:wooden_shovel",
    "minecraft:wooden_hoe",
    "minecraft:wooden_axe",
    "minecraft:wooden_sword",
    "minecraft:wooden_pickaxe",
    "mm:coal_infuser_rotation_output",
    "mm:spirit_alchemy_rotation_output",
    "mm:tri_ore_transmuter_rotation_output",
    "mm:squeezer_rotation_output",
    "mm:squeezer_fluid_input",
    /^exnihilosequentia:.*_mesh$/,
    /^exnihilosequentia:.*_crook$/,
    /^exnihilosequentia:.*_sieve$/,
    /^exnihilosequentia:.*_pieces$/,
    /^exnihilosequentia:.*_ingot$/,
    /^exnihilosequentia:.*_nugget$/,
    /^exnihilosequentia:raw.*$/,
    /^exnihilosequentia:crushed.*$/,
    "exnihilosequentia:infested_leaves",
    "exnihilosequentia:infesting_leaves",
    "exnihilosequentia:dust",
    "exnihilosequentia:tuff_pebble",
    "exnihilosequentia:stone_pebble",
    "exnihilosequentia:netherrack_pebble",
    "exnihilosequentia:granite_pebble",
    "exnihilosequentia:end_stone_pebble",
    "exnihilosequentia:dripstone_pebble",
    "exnihilosequentia:cooked_silkworm",
    "exnihilosequentia:silkworm",
    "exnihilosequentia:basalt_pebble",
    "exnihilosequentia:blackstone_pebble",
    "exnihilosequentia:calcite_pebble",
    "exnihilosequentia:deepslate_pebble",
    "exnihilosequentia:diorite_pebble",
    /^thermal:dynamo_.*$/


];



global.colors = [
    "black",
    "blue",
    "brown",
    "cyan",
    "gray",
    "green",
    "light_blue",
    "light_gray",
    "lime",
    "magenta",
    "orange",
    "pink",
    "purple",
    "red",
    "white",
    "yellow",
];

